### ISSUE TITLE
[BUG] Ratio of images in exr sequence is not correct

### ISSUE THREAD

**Issue by Ophtis** [romainaugier/OpenViewer#7]
**Describe the bug**
Load an Exr sequence produces broken image ratio in first 24 images (and other portion of the sequence)

Besides, sequence number is not starting from 001. (but start is 1 in the playbar)

**To Reproduce**
1. Load exr sequence
2. Play with cache enabled

Same sequence is working with png. (except the playbar detail)

**Screenshots**
![2022-01-12 14_49_25-Clipboard](https://user-images.githubusercontent.com/16814707/149152606-bee4280d-c3b9-4211-888a-eed89546db7a.png)

**Console Log**
```
[DIAGNOSTIC] 14:44:40 : [MAIN] : Initializing Logger
[DIAGNOSTIC] 14:44:40 : [OCIO] : Initializing OCIO
[WARNING] 14:44:40 : [OCIO] : Environment variable can't be found. Using default shipped configuration
[DIAGNOSTIC] 14:44:40 : [LOADER] : Initializing loader
[DIAGNOSTIC] 14:44:50 : [LOADER] : Loading media D:/sophie/openViewer/tests/work_v007
[DIAGNOSTIC] 14:44:50 : [LOADER] : Directory detected
[DIAGNOSTIC] 14:44:50 : [CACHE] : Initializing minimal Image Cache (30.11 MB)
[DIAGNOSTIC] 14:44:50 : [DISPLAY] : Initializing display 1
[DIAGNOSTIC] 14:45:24 : [CACHE] : Image Cache resized (500.00 MB)
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: build from commit cf756e03007ce291bd19b6e62a55c90b1ddd1975

**Comment by romainaugier** [comment]
Solved by commit 63a784e18d51f21ff494aab4dacf07cbcbb2c37b.
